### ISSUE TITLE
Stuck in progress

### ISSUE THREAD

**Issue by barracuda500GB** [MikeEmmett/InvokeAI#4]
Any action performed inside invokeai seems to get stuck 'in progress' and doesn't advance until you refresh the browser.
This applies to downloading or generating images. It works, but you'll need to constantly refresh your browser.
I'm using the latest build.

and this is what appear in the console:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/dispatcher.py", line 52, in task
    await asyncio.gather(*[handler.handle((event_name, payload)) for handler in handlers])
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/handlers/local.py", line 195, in handle
    with create_span_for_handle_fn(
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/otel/utils.py", line 43, in create_span_for_handle_fn
    remote_ctx = propagate.extract(payload)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagate/__init__.py", line 101, in extract
    return get_global_textmap().extract(carrier, context, getter=getter)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagators/composite.py", line 52, in extract
    context = propagator.extract(carrier, context, getter=getter)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/trace/propagation/tracecontext.py", line 49, in extract
    header = getter.get(carrier, self._TRACEPARENT_HEADER_NAME)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagators/textmap.py", line 87, in get
    val = carrier.get(key, None)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 811, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'InvocationCompleteEvent' object has no attribute 'get'
```

**Comment by ImMikeEmmett** [comment]
Hello Barracuda!

I have run this, this morning. it is now failing.... Even with version 5.0.0 which worked last week...

Looked through install logs,
It is now complaining that a dependency missing, added this to the install script, Tested with V5.0.2 and v5.0.0  in both "Temp" and "Google Drive" installs and it is working again.

Added line of code:
#Install a dependency 
!apt install python3.10-venv

**Comment by ImMikeEmmett** [comment]
Update about this one.
It appears that the new VENV isn't compatible with the old one. (It should work but loads VERY slowly)
If you are using a "Google Drive" install you may have to re-build by deleting the install.

**Comment by ImMikeEmmett** [comment]
Okay, that hasn't worked well enough to consider it "Closed"  Re-opening.

**Comment by ImMikeEmmett** [comment]
Hello!
Coming back to this.
It is now working as expected WITH VERSION 5.1.0  ("DEFAULT" version at time of posting)
NOTE: IF USING GOOGLE DRIVE, A FULL REBUILD MAY BE NEEDED, backup any IMAGES / MODELS - DELETE + RE-RUN.
