### ISSUE TITLE
.venv/bin/python: bad interpreter: Permission denied

### ISSUE THREAD

**Issue by elihanani** [MikeEmmett/InvokeAI#5]
First, let me thank you for putting this together.

Every attempt to launch the application with NGROK results in the error message below. I tried starting with and reinstalling with **!sudo**, but no difference.

`/content/drive/MyDrive/invokeai/invokeaiapp
InvokeAI Public URL: https://ff24-34-82-219-125.ngrok-free.app/
/bin/bash: /content/drive/MyDrive/invokeai/invokeaiapp/.venv/bin/invokeai-web: /content/drive/MyDrive/invokeai/invokeaiapp/.venv/bin/python: bad interpreter: Permission denied`

The terminal will show the error below. 

My only option is to install Cloudflare and launch with that, but it is very slow and sometimes fails to generate with flux models. With a clean install, some items, such as the clip-vit-large-patch14-text-encoder for flux, fail to download from their marketplace. Also, image generation are not as consistent. Please advise.

`ask exception was never retrieved
future: <Task finished name='Task-485' coro=<_dispatch_as_task.<locals>.task() done, defined at /usr/local/lib/python3.10/dist-packages/fastapi_events/dispatcher.py:51> exception=AttributeError("'BatchEnqueuedEvent' object has no attribute 'get'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/dispatcher.py", line 52, in task
    await asyncio.gather(*[handler.handle((event_name, payload)) for handler in handlers])
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/handlers/local.py", line 195, in handle
    with create_span_for_handle_fn(
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/otel/utils.py", line 43, in create_span_for_handle_fn
    remote_ctx = propagate.extract(payload)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagate/__init__.py", line 101, in extract
    return get_global_textmap().extract(carrier, context, getter=getter)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagators/composite.py", line 52, in extract
    context = propagator.extract(carrier, context, getter=getter)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/trace/propagation/tracecontext.py", line 49, in extract
    header = getter.get(carrier, self._TRACEPARENT_HEADER_NAME)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagators/textmap.py", line 86, in get
    val = carrier.get(key, None)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 811, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'BatchEnqueuedEvent' object has no attribute 'get'
[2024-11-09 23:32:52,567]::[uvicorn.access]::INFO --> 60.50.231.248:0 - "GET /api/v1/queue/default/counts_by_destination?destination=canvas HTTP/1.1" 200
[2024-11-09 23:32:52,577]::[uvicorn.access]::INFO --> 60.50.231.248:0 - "GET /api/v1/queue/default/list HTTP/1.1" 200
[2024-11-09 23:32:52,620]::[uvicorn.access]::INFO --> 60.50.231.248:0 - "GET /assets/images/invoke-alert-favicon.svg HTTP/1.1" 200
[2024-11-09 23:32:52,854]::[uvicorn.access]::INFO --> 60.50.231.248:0 - "GET /api/v1/queue/default/current HTTP/1.1" 200
Task exception was never retrieved
future: <Task finished name='Task-513' coro=<_dispatch_as_task.<locals>.task() done, defined at /usr/local/lib/python3.10/dist-packages/fastapi_events/dispatcher.py:51> exception=AttributeError("'QueueItemStatusChangedEvent' object has no attribute 'get'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/dispatcher.py", line 52, in task
    await asyncio.gather(*[handler.handle((event_name, payload)) for handler in handlers])
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/handlers/local.py", line 195, in handle
    with create_span_for_handle_fn(
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/otel/utils.py", line 43, in create_span_for_handle_fn
    remote_ctx = propagate.extract(payload)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagate/__init__.py", line 101, in extract
    return get_global_textmap().extract(carrier, context, getter=getter)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagators/composite.py", line 52, in extract
    context = propagator.extract(carrier, context, getter=getter)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/trace/propagation/tracecontext.py", line 49, in extract
    header = getter.get(carrier, self._TRACEPARENT_HEADER_NAME)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagators/textmap.py", line 86, in get
    val = carrier.get(key, None)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 811, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'QueueItemStatusChangedEvent' object has no attribute 'get'
Task exception was never retrieved
future: <Task finished name='Task-515' coro=<_dispatch_as_task.<locals>.task() done, defined at /usr/local/lib/python3.10/dist-packages/fastapi_events/dispatcher.py:51> exception=AttributeError("'InvocationStartedEvent' object has no attribute 'get'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/dispatcher.py", line 52, in task
    await asyncio.gather(*[handler.handle((event_name, payload)) for handler in handlers])
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/handlers/local.py", line 195, in handle
    with create_span_for_handle_fn(
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/otel/utils.py", line 43, in create_span_for_handle_fn
    remote_ctx = propagate.extract(payload)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagate/__init__.py", line 101, in extract
    return get_global_textmap().extract(carrier, context, getter=getter)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagators/composite.py", line 52, in extract
    context = propagator.extract(carrier, context, getter=getter)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/trace/propagation/tracecontext.py", line 49, in extract
    header = getter.get(carrier, self._TRACEPARENT_HEADER_NAME)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagators/textmap.py", line 86, in get
    val = carrier.get(key, None)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 811, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'InvocationStartedEvent' object has no attribute 'get'
Task exception was never retrieved
future: <Task finished name='Task-517' coro=<_dispatch_as_task.<locals>.task() done, defined at /usr/local/lib/python3.10/dist-packages/fastapi_events/dispatcher.py:51> exception=AttributeError("'InvocationCompleteEvent' object has no attribute 'get'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/dispatcher.py", line 52, in task
    await asyncio.gather(*[handler.handle((event_name, payload)) for handler in handlers])
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/handlers/local.py", line 195, in handle
    with create_span_for_handle_fn(
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/otel/utils.py", line 43, in create_span_for_handle_fn
    remote_ctx = propagate.extract(payload)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagate/__init__.py", line 101, in extract
    return get_global_textmap().extract(carrier, context, getter=getter)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagators/composite.py", line 52, in extract
    context = propagator.extract(carrier, context, getter=getter)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/trace/propagation/tracecontext.py", line 49, in extract
    header = getter.get(carrier, self._TRACEPARENT_HEADER_NAME)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagators/textmap.py", line 86, in get
    val = carrier.get(key, None)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 811, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'InvocationCompleteEvent' object has no attribute 'get'
Task exception was never retrieved
future: <Task finished name='Task-519' coro=<_dispatch_as_task.<locals>.task() done, defined at /usr/local/lib/python3.10/dist-packages/fastapi_events/dispatcher.py:51> exception=AttributeError("'InvocationStartedEvent' object has no attribute 'get'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/dispatcher.py", line 52, in task
    await asyncio.gather(*[handler.handle((event_name, payload)) for handler in handlers])
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/handlers/local.py", line 195, in handle
    with create_span_for_handle_fn(
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/otel/utils.py", line 43, in create_span_for_handle_fn
    remote_ctx = propagate.extract(payload)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagate/__init__.py", line 101, in extract
    return get_global_textmap().extract(carrier, context, getter=getter)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagators/composite.py", line 52, in extract
    context = propagator.extract(carrier, context, getter=getter)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/trace/propagation/tracecontext.py", line 49, in extract
    header = getter.get(carrier, self._TRACEPARENT_HEADER_NAME)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagators/textmap.py", line 86, in get
    val = carrier.get(key, None)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 811, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'InvocationStartedEvent' object has no attribute 'get'
Task exception was never retrieved
future: <Task finished name='Task-520' coro=<_dispatch_as_task.<locals>.task() done, defined at /usr/local/lib/python3.10/dist-packages/fastapi_events/dispatcher.py:51> exception=AttributeError("'InvocationCompleteEvent' object has no attribute 'get'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/dispatcher.py", line 52, in task
    await asyncio.gather(*[handler.handle((event_name, payload)) for handler in handlers])
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/handlers/local.py", line 195, in handle
    with create_span_for_handle_fn(
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/otel/utils.py", line 43, in create_span_for_handle_fn
    remote_ctx = propagate.extract(payload)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagate/__init__.py", line 101, in extract
    return get_global_textmap().extract(carrier, context, getter=getter)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagators/composite.py", line 52, in extract
    context = propagator.extract(carrier, context, getter=getter)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/trace/propagation/tracecontext.py", line 49, in extract
    header = getter.get(carrier, self._TRACEPARENT_HEADER_NAME)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagators/textmap.py", line 86, in get
    val = carrier.get(key, None)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 811, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'InvocationCompleteEvent' object has no attribute 'get'
Task exception was never retrieved
future: <Task finished name='Task-523' coro=<_dispatch_as_task.<locals>.task() done, defined at /usr/local/lib/python3.10/dist-packages/fastapi_events/dispatcher.py:51> exception=AttributeError("'InvocationStartedEvent' object has no attribute 'get'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/dispatcher.py", line 52, in task
    await asyncio.gather(*[handler.handle((event_name, payload)) for handler in handlers])
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/handlers/local.py", line 195, in handle
    with create_span_for_handle_fn(
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/otel/utils.py", line 43, in create_span_for_handle_fn
    remote_ctx = propagate.extract(payload)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagate/__init__.py", line 101, in extract
    return get_global_textmap().extract(carrier, context, getter=getter)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagators/composite.py", line 52, in extract
    context = propagator.extract(carrier, context, getter=getter)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/trace/propagation/tracecontext.py", line 49, in extract
    header = getter.get(carrier, self._TRACEPARENT_HEADER_NAME)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagators/textmap.py", line 86, in get
    val = carrier.get(key, None)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 811, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'InvocationStartedEvent' object has no attribute 'get'
Task exception was never retrieved
future: <Task finished name='Task-524' coro=<_dispatch_as_task.<locals>.task() done, defined at /usr/local/lib/python3.10/dist-packages/fastapi_events/dispatcher.py:51> exception=AttributeError("'InvocationCompleteEvent' object has no attribute 'get'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/dispatcher.py", line 52, in task
    await asyncio.gather(*[handler.handle((event_name, payload)) for handler in handlers])
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/handlers/local.py", line 195, in handle
    with create_span_for_handle_fn(
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/otel/utils.py", line 43, in create_span_for_handle_fn
    remote_ctx = propagate.extract(payload)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagate/__init__.py", line 101, in extract
    return get_global_textmap().extract(carrier, context, getter=getter)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagators/composite.py", line 52, in extract
    context = propagator.extract(carrier, context, getter=getter)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/trace/propagation/tracecontext.py", line 49, in extract
    header = getter.get(carrier, self._TRACEPARENT_HEADER_NAME)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagators/textmap.py", line 86, in get
    val = carrier.get(key, None)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 811, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'InvocationCompleteEvent' object has no attribute 'get'
Task exception was never retrieved
future: <Task finished name='Task-527' coro=<_dispatch_as_task.<locals>.task() done, defined at /usr/local/lib/python3.10/dist-packages/fastapi_events/dispatcher.py:51> exception=AttributeError("'InvocationStartedEvent' object has no attribute 'get'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/dispatcher.py", line 52, in task
    await asyncio.gather(*[handler.handle((event_name, payload)) for handler in handlers])
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/handlers/local.py", line 195, in handle
    with create_span_for_handle_fn(
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/otel/utils.py", line 43, in create_span_for_handle_fn
    remote_ctx = propagate.extract(payload)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagate/__init__.py", line 101, in extract
    return get_global_textmap().extract(carrier, context, getter=getter)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagators/composite.py", line 52, in extract
    context = propagator.extract(carrier, context, getter=getter)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/trace/propagation/tracecontext.py", line 49, in extract
    header = getter.get(carrier, self._TRACEPARENT_HEADER_NAME)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagators/textmap.py", line 86, in get
    val = carrier.get(key, None)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 811, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'InvocationStartedEvent' object has no attribute 'get'
Task exception was never retrieved
future: <Task finished name='Task-528' coro=<_dispatch_as_task.<locals>.task() done, defined at /usr/local/lib/python3.10/dist-packages/fastapi_events/dispatcher.py:51> exception=AttributeError("'InvocationCompleteEvent' object has no attribute 'get'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/dispatcher.py", line 52, in task
    await asyncio.gather(*[handler.handle((event_name, payload)) for handler in handlers])
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/handlers/local.py", line 195, in handle
    with create_span_for_handle_fn(
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/otel/utils.py", line 43, in create_span_for_handle_fn
    remote_ctx = propagate.extract(payload)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagate/__init__.py", line 101, in extract
    return get_global_textmap().extract(carrier, context, getter=getter)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagators/composite.py", line 52, in extract
    context = propagator.extract(carrier, context, getter=getter)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/trace/propagation/tracecontext.py", line 49, in extract
    header = getter.get(carrier, self._TRACEPARENT_HEADER_NAME)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagators/textmap.py", line 86, in get
    val = carrier.get(key, None)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 811, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'InvocationCompleteEvent' object has no attribute 'get'
Task exception was never retrieved
future: <Task finished name='Task-531' coro=<_dispatch_as_task.<locals>.task() done, defined at /usr/local/lib/python3.10/dist-packages/fastapi_events/dispatcher.py:51> exception=AttributeError("'InvocationStartedEvent' object has no attribute 'get'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/dispatcher.py", line 52, in task
    await asyncio.gather(*[handler.handle((event_name, payload)) for handler in handlers])
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/handlers/local.py", line 195, in handle
    with create_span_for_handle_fn(
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/otel/utils.py", line 43, in create_span_for_handle_fn
    remote_ctx = propagate.extract(payload)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagate/__init__.py", line 101, in extract
    return get_global_textmap().extract(carrier, context, getter=getter)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagators/composite.py", line 52, in extract
    context = propagator.extract(carrier, context, getter=getter)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/trace/propagation/tracecontext.py", line 49, in extract
    header = getter.get(carrier, self._TRACEPARENT_HEADER_NAME)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagators/textmap.py", line 86, in get
    val = carrier.get(key, None)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 811, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'InvocationStartedEvent' object has no attribute 'get'
Task exception was never retrieved
future: <Task finished name='Task-532' coro=<_dispatch_as_task.<locals>.task() done, defined at /usr/local/lib/python3.10/dist-packages/fastapi_events/dispatcher.py:51> exception=AttributeError("'ModelLoadStartedEvent' object has no attribute 'get'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/dispatcher.py", line 52, in task
    await asyncio.gather(*[handler.handle((event_name, payload)) for handler in handlers])
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/handlers/local.py", line 195, in handle
    with create_span_for_handle_fn(
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/otel/utils.py", line 43, in create_span_for_handle_fn
    remote_ctx = propagate.extract(payload)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagate/__init__.py", line 101, in extract
    return get_global_textmap().extract(carrier, context, getter=getter)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagators/composite.py", line 52, in extract
    context = propagator.extract(carrier, context, getter=getter)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/trace/propagation/tracecontext.py", line 49, in extract
    header = getter.get(carrier, self._TRACEPARENT_HEADER_NAME)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagators/textmap.py", line 86, in get
    val = carrier.get(key, None)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 811, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'ModelLoadStartedEvent' object has no attribute 'get'
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Task exception was never retrieved
future: <Task finished name='Task-535' coro=<_dispatch_as_task.<locals>.task() done, defined at /usr/local/lib/python3.10/dist-packages/fastapi_events/dispatcher.py:51> exception=AttributeError("'ModelLoadCompleteEvent' object has no attribute 'get'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/dispatcher.py", line 52, in task
    await asyncio.gather(*[handler.handle((event_name, payload)) for handler in handlers])
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/handlers/local.py", line 195, in handle
    with create_span_for_handle_fn(
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/otel/utils.py", line 43, in create_span_for_handle_fn
    remote_ctx = propagate.extract(payload)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagate/__init__.py", line 101, in extract
    return get_global_textmap().extract(carrier, context, getter=getter)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagators/composite.py", line 52, in extract
    context = propagator.extract(carrier, context, getter=getter)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/trace/propagation/tracecontext.py", line 49, in extract
    header = getter.get(carrier, self._TRACEPARENT_HEADER_NAME)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagators/textmap.py", line 86, in get
    val = carrier.get(key, None)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 811, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'ModelLoadCompleteEvent' object has no attribute 'get'
Task exception was never retrieved
future: <Task finished name='Task-537' coro=<_dispatch_as_task.<locals>.task() done, defined at /usr/local/lib/python3.10/dist-packages/fastapi_events/dispatcher.py:51> exception=AttributeError("'ModelLoadStartedEvent' object has no attribute 'get'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/dispatcher.py", line 52, in task
    await asyncio.gather(*[handler.handle((event_name, payload)) for handler in handlers])
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/handlers/local.py", line 195, in handle
    with create_span_for_handle_fn(
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/otel/utils.py", line 43, in create_span_for_handle_fn
    remote_ctx = propagate.extract(payload)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagate/__init__.py", line 101, in extract
    return get_global_textmap().extract(carrier, context, getter=getter)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagators/composite.py", line 52, in extract
    context = propagator.extract(carrier, context, getter=getter)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/trace/propagation/tracecontext.py", line 49, in extract
    header = getter.get(carrier, self._TRACEPARENT_HEADER_NAME)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagators/textmap.py", line 86, in get
    val = carrier.get(key, None)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 811, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'ModelLoadStartedEvent' object has no attribute 'get'`

**Comment by ImMikeEmmett** [comment]
Okay, I managed to trigger this by first pre-running an older (pre Invoke V5) version. and trying to upgrade to the latest version, This does transition a VENV version, so its permissions don't work well.
Sadly My only recommendation will be to backup images. Delete the google drive folder, and re-create.
Running it with the "Rebuild" flag applied may sort this, it depends on the current version you are running.

**Comment by ImMikeEmmett** [comment]
This Issue is to do with the users specific setup, a rebuild will be needed.
However I have added a new connection method that is far more forgiving when it comes to permissions to help reduce this type of issue.

**Comment by elihanani** [comment]
Thank you so much. 

It was not working on a fresh install due to a model install error, but everything is working properly, with that being fixed by InvokeAI. Thanks agian.

https://www.youtube.com/watch?v=3EgYD07JdOQ
